# vis hottest day  2018.8.27

In [1]:
import pandas as pd
import numpy as np
import datetime
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [2]:
data = pd.read_csv("./final_input/rt.csv")
df = data

In [3]:
backupdf = df

In [4]:
df

Unnamed: 0     temp  humidity    PM25    SO2  partical    light  \
0                0  27.6130   44.7610   1.031  0.000         0  16.7880   
1                1  23.1775   76.4100   0.500  0.112         0  42.2135   
2                2  19.8890   82.5070  14.220 -0.188         0  54.0540   
3                3  27.6340   42.4955   0.797  0.000         0   1.1670   
5                5  22.3700   80.9020   3.460  0.521         0  51.2830   
...            ...      ...       ...     ...    ...       ...      ...   
839921      839921  31.9640   55.8400   2.481 -0.265         0  38.8875   
839923      839923  17.2730  100.0000   0.032 -0.143         0  54.7505   
839924      839924  25.9540   48.9140   0.456 -0.097         0  25.0870   
839925      839925  22.4645   73.9320   2.323  0.039         0  12.7880   
839926      839926  20.3190  100.0000   0.654  0.132         0  47.0970   

               band1         band2         band3         band4         band5  \
0       12431.666667  13346.666667  15138.333333  15609.666667  18002.333333   
1       10858.604167  11400.708333  12351.395833  12788.937500  14684.520833   
2       10666.125000  11290.916667  11998.750000  12526.291667  13784.875000   
3       12429.625000  13341.125000  15080.750000  15566.375000  18005.500000   
5       11814.666667  12262.916667  13277.500000  13790.916667  16606.500000   
...              ...           ...           ...           ...           ...   
839921  10293.312500  11128.562500  13242.437500  14178.250000  14639.625000   
839923   9888.770833  10411.541667  11762.729167  12221.500000  13864.687500   
839924  10404.916667  10954.208333  12037.333333  12421.166667  13484.875000   
839925   8300.833333   8193.500000   8192.500000   7772.833333   7687.500000   
839926   9742.250000  10202.000000  10931.750000  11228.500000  12888.500000   

               band6         band7  dist_to_cent   tod  dss  year  
0       18244.000000  16106.666667      0.146792   905    2  2018  
1       15126.562500  13924.645833      0.160694  1265    3  2018  
2       14593.083333  13688.333333      0.106742  1215    0  2018  
3       18236.875000  16074.375000      0.146792   645    4  2018  
5       20853.166667  18781.666667      0.045630   685    6  2018  
...              ...           ...           ...   ...  ...   ...  
839921  16643.312500  16666.500000      0.046002  1095   91  2018  
839923  14261.541667  12940.458333      0.164218  1035   93  2018  
839924  14741.291667  13607.250000      0.118475  1045   92  2018  
839925   7392.666667   7187.166667      0.143288   325   90  2018  
839926  13146.750000  12211.500000      0.104955   855   94  2018  

[770290 rows x 18 columns]

In [5]:
Y = df["temp"]
data_Y = np.array(Y.tolist())
data_Y

array([27.613 , 23.1775, 19.889 , ..., 25.954 , 22.4645, 20.319 ])

In [6]:
day = datetime.datetime(year = 2018, month = 8, day = 27) - datetime.datetime(year = 2018, month = 6, day = 21)

In [7]:
h_df = df[(df["dss"]==day.days)]

In [8]:
h_df

Unnamed: 0     temp  humidity   PM25    SO2  partical    light  \
590424      590424  28.2245   67.1720  0.774  0.149         0  54.2920   
590431      590431  29.5900   53.9800  1.320  0.277         0  54.0830   
590447      590447  29.1980   73.1360  0.065  0.000         0   0.1390   
590449      590449  32.2470   57.8040  2.958  0.069         0   0.0300   
590453      590453  30.3190   68.2340  0.681  0.000         0  20.8340   
...            ...      ...       ...    ...    ...       ...      ...   
675200      675200  29.6980   70.6370  5.199  0.124         0  24.1895   
675202      675202  31.6520   61.1330  2.648  0.076         0  12.8975   
675276      675276  29.1700   80.8180  4.427  0.698         0  56.7305   
675281      675281  35.2610   43.9365  2.083  0.000         0  56.1595   
675302      675302  33.7000   46.7100  0.802  0.148         0  80.0555   

             band1       band2       band3       band4       band5  \
590424  11278.4375  12082.8750  13271.8750  14043.6250  15056.4375   
590431  11674.4375  12357.9375  13159.6875  13598.1250  15073.2500   
590447  10966.9375  11778.9375  12974.5000  13514.8750  14204.8750   
590449   9937.6250  10232.3125  11013.9375  11314.8125  12331.2500   
590453  10553.1250  10876.1875  12129.5000  12447.0000  14983.1875   
...            ...         ...         ...         ...         ...   
675200   9201.1875   9393.8125   9893.0625   9854.8125  10604.1875   
675202   9888.3750  10357.3125  11121.1250  11475.0000  16525.0625   
675276  11296.7500  11659.1875  12531.7500  12974.6250  15868.0625   
675281   8921.3750   9295.5000   9778.7500   9507.5000  15168.8750   
675302   9209.6875   9727.3125  10615.3125  10865.6875  12980.8750   

             band6       band7  dist_to_cent   tod  dss  year  
590424  15735.0000  14368.8750      0.016827   775   67  2018  
590431  15737.0625  14787.8750      0.066182   885   67  2018  
590447  14385.6875  13510.2500      0.102200   295   67  2018  
590449  12214.5000  11709.7500      0.026246   235   67  2018  
590453  14951.1250  13541.3750      0.056800   285   67  2018  
...            ...         ...           ...   ...  ...   ...  
675200  10375.0000   9679.3125      0.143288   285   67  2018  
675202  13917.6250  11438.5625      0.095115   195   67  2018  
675276  20708.6875  18627.1875      0.045630   835   67  2018  
675281  12587.3125  10802.1250      0.094690  1245   67  2018  
675302  13220.3750  12222.8125      0.074326  1405   67  2018  

[6515 rows x 18 columns]

In [9]:
nodes = set(list(h_df["dist_to_cent"]))

In [10]:
nodes

{0.01276894835136991,
 0.013833445919211224,
 0.016827008884521398,
 0.02624649508031337,
 0.02665077899425396,
 0.02814005806675368,
 0.028574218064554225,
 0.03165111942728804,
 0.03660962109883422,
 0.03682355227297375,
 0.04563019929828095,
 0.046002092756760496,
 0.04704156529070879,
 0.05004631048339756,
 0.05160150370871158,
 0.05304544083144331,
 0.05466935577634058,
 0.055166764170108025,
 0.05546368574157292,
 0.05546732447123371,
 0.056799521344820574,
 0.06618179260189604,
 0.07432589041512055,
 0.08030509993767819,
 0.0832280169474082,
 0.08474327471841163,
 0.08535545331141403,
 0.08679985973490867,
 0.08766786941633818,
 0.0916556312563504,
 0.09239834874065628,
 0.09469049587471616,
 0.09511527930358622,
 0.09922942112598876,
 0.10040099974104247,
 0.10220022927566684,
 0.10495457391179436,
 0.1184749061573858,
 0.1289635463919986,
 0.13042697390494587,
 0.13212533033828186,
 0.1432880425052985,
 0.14670848074328124,
 0.1511497597814849,
 0.1606943167445655,
 0.16421836

In [11]:
for node in nodes:
    curr_df = h_df[h_df["dist_to_cent"]==node]
    temp_list = list(curr_df["temp"])
    print("node dist_to_cent: " + str(node) + " | Temp: "+ str(max(temp_list)))

node dist_to_cent: 0.0916556312563504 | Temp: 35.49
node dist_to_cent: 0.08535545331141403 | Temp: 36.4095
node dist_to_cent: 0.05466935577634058 | Temp: 35.28650000000001
node dist_to_cent: 0.08679985973490867 | Temp: 35.575
node dist_to_cent: 0.07432589041512055 | Temp: 35.69
node dist_to_cent: 0.164218363543788 | Temp: 36.104
node dist_to_cent: 0.09239834874065628 | Temp: 34.379000000000005
node dist_to_cent: 0.02814005806675368 | Temp: 35.745
node dist_to_cent: 0.05160150370871158 | Temp: 36.655
node dist_to_cent: 0.09922942112598876 | Temp: 36.686
node dist_to_cent: 0.05546732447123371 | Temp: 37.178
node dist_to_cent: 0.055166764170108025 | Temp: 35.163000000000004
node dist_to_cent: 0.05304544083144331 | Temp: 35.64
node dist_to_cent: 0.09511527930358622 | Temp: 36.80250000000001
node dist_to_cent: 0.046002092756760496 | Temp: 35.961
node dist_to_cent: 0.04563019929828095 | Temp: 36.162
node dist_to_cent: 0.03682355227297375 | Temp: 37.174
node dist_to_cent: 0.10495457391179436 

# Normalizaiton before prediction

In [12]:
def column(matrix, i):
    return [row[i] for row in matrix]
def norm(lst):
    min_v = min(lst)
    max_v = max(lst)
    norm_lst = [(i-min_v)/(max_v-min_v) for i in lst]
    return norm_lst

In [13]:
Y = df["temp"]
data_Y = np.array(Y.tolist())
data_Y

array([27.613 , 23.1775, 19.889 , ..., 25.954 , 22.4645, 20.319 ])

In [14]:
df.drop(df.columns[[0, 1]], axis=1, inplace=True)
data_X = df.values

/Users/carnivalbug/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [15]:
curr = column(data_X, 0)
rt = np.array([norm(curr)])
for i in range(1, 15):
    if (i!=3):
        curr = column(data_X, i)
        rt = np.concatenate((rt, np.array([norm(curr)])))

In [16]:
final_rt = rt.T
final_rt.shape
data_X = final_rt

In [17]:
data_X

array([[0.66410697, 0.01444402, 0.53919185, ..., 0.60230189, 0.62937063,
        0.0212766 ],
       [0.8073216 , 0.00700486, 0.53967126, ..., 0.66472656, 0.88111888,
        0.03191489],
       [0.83491108, 0.19921826, 0.53838712, ..., 0.42247155, 0.84615385,
        0.        ],
       ...,
       [0.68289968, 0.00638843, 0.53877665, ..., 0.47515304, 0.72727273,
        0.9787234 ],
       [0.79610842, 0.03254459, 0.53935879, ..., 0.58656894, 0.22377622,
        0.95744681],
       [0.91406851, 0.00916236, 0.53975687, ..., 0.41444407, 0.59440559,
        1.        ]])

In [18]:
data_Y.shape

(770290,)

# Random Forest Prediction

In [20]:
X_train, X_test, y_train, y_test = train_test_split(data_X, np.array(Y), test_size=0.2, random_state=42)
y_train  = y_train.astype(float)
y_test  = y_test.astype(float)
batch_size =len(X_train)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape )

(616232, 14) (616232,) (154058, 14) (154058,)


In [21]:
regr = RandomForestRegressor(max_depth=16, random_state=0)
regr.fit(X_train, y_train)

RandomForestRegressor(max_depth=16, random_state=0)

In [22]:
predicted_Y = regr.predict(data_X)

In [23]:
predicted_Y.shape

(770290,)

In [24]:
backupdf["rt_temp"] = list(predicted_Y)

<ipython-input-24-ca9d4bd1f99f>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  backupdf["rt_temp"] = list(predicted_Y)


In [25]:
backupdf

humidity    PM25    SO2  partical    light         band1  \
0        44.7610   1.031  0.000         0  16.7880  12431.666667   
1        76.4100   0.500  0.112         0  42.2135  10858.604167   
2        82.5070  14.220 -0.188         0  54.0540  10666.125000   
3        42.4955   0.797  0.000         0   1.1670  12429.625000   
5        80.9020   3.460  0.521         0  51.2830  11814.666667   
...          ...     ...    ...       ...      ...           ...   
839921   55.8400   2.481 -0.265         0  38.8875  10293.312500   
839923  100.0000   0.032 -0.143         0  54.7505   9888.770833   
839924   48.9140   0.456 -0.097         0  25.0870  10404.916667   
839925   73.9320   2.323  0.039         0  12.7880   8300.833333   
839926  100.0000   0.654  0.132         0  47.0970   9742.250000   

               band2         band3         band4         band5         band6  \
0       13346.666667  15138.333333  15609.666667  18002.333333  18244.000000   
1       11400.708333  12351.395833  12788.937500  14684.520833  15126.562500   
2       11290.916667  11998.750000  12526.291667  13784.875000  14593.083333   
3       13341.125000  15080.750000  15566.375000  18005.500000  18236.875000   
5       12262.916667  13277.500000  13790.916667  16606.500000  20853.166667   
...              ...           ...           ...           ...           ...   
839921  11128.562500  13242.437500  14178.250000  14639.625000  16643.312500   
839923  10411.541667  11762.729167  12221.500000  13864.687500  14261.541667   
839924  10954.208333  12037.333333  12421.166667  13484.875000  14741.291667   
839925   8193.500000   8192.500000   7772.833333   7687.500000   7392.666667   
839926  10202.000000  10931.750000  11228.500000  12888.500000  13146.750000   

               band7  dist_to_cent   tod  dss  year    rt_temp  
0       16106.666667      0.146792   905    2  2018  27.596124  
1       13924.645833      0.160694  1265    3  2018  23.088887  
2       13688.333333      0.106742  1215    0  2018  19.513122  
3       16074.375000      0.146792   645    4  2018  27.662912  
5       18781.666667      0.045630   685    6  2018  22.475081  
...              ...           ...   ...  ...   ...        ...  
839921  16666.500000      0.046002  1095   91  2018  31.324417  
839923  12940.458333      0.164218  1035   93  2018  17.442218  
839924  13607.250000      0.118475  1045   92  2018  25.607091  
839925   7187.166667      0.143288   325   90  2018  22.462886  
839926  12211.500000      0.104955   855   94  2018  19.998508  

[770290 rows x 17 columns]

In [26]:
h_df = backupdf[(backupdf["dss"]==day.days)]

In [27]:
print("random forest prediction")
for node in nodes:
    curr_df = h_df[h_df["dist_to_cent"]==node]
    temp_list = list(curr_df["rt_temp"])
    print("node dist_to_cent: " + str(node) + " | Temp: "+ str(max(temp_list)))

random forest prediction
node dist_to_cent: 0.0916556312563504 | Temp: 35.5577942283592
node dist_to_cent: 0.08535545331141403 | Temp: 35.72625974030772
node dist_to_cent: 0.05466935577634058 | Temp: 35.07904220817748
node dist_to_cent: 0.08679985973490867 | Temp: 33.95642860131205
node dist_to_cent: 0.07432589041512055 | Temp: 35.5577942283592
node dist_to_cent: 0.164218363543788 | Temp: 35.52105694175226
node dist_to_cent: 0.09239834874065628 | Temp: 35.05216793783957
node dist_to_cent: 0.02814005806675368 | Temp: 35.145399299412496
node dist_to_cent: 0.05160150370871158 | Temp: 36.40063573983418
node dist_to_cent: 0.09922942112598876 | Temp: 36.085028391363544
node dist_to_cent: 0.05546732447123371 | Temp: 36.121440612552426
node dist_to_cent: 0.055166764170108025 | Temp: 35.00994943777095
node dist_to_cent: 0.05304544083144331 | Temp: 35.07480568272638
node dist_to_cent: 0.09511527930358622 | Temp: 35.62341660999585
node dist_to_cent: 0.046002092756760496 | Temp: 34.9640293283769
n