# 2018, Regression

In [37]:
import pandas as pd
import numpy as np

In [38]:
data = pd.read_csv("./final_input/rt.csv")

In [39]:
df = data

In [40]:
Y = df["temp"]
data_Y = np.array(Y.tolist())
data_Y

array([27.613 , 23.1775, 19.889 , ..., 25.954 , 22.4645, 20.319 ])

In [41]:
df.drop(df.columns[[0, 1]], axis=1, inplace=True)

/Users/carnivalbug/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [42]:
data_X = df.values

In [43]:
data_Y

array([27.613 , 23.1775, 19.889 , ..., 25.954 , 22.4645, 20.319 ])

In [44]:
data_X

array([[ 4.4761e+01,  1.0310e+00,  0.0000e+00, ...,  9.0500e+02,
         2.0000e+00,  2.0180e+03],
       [ 7.6410e+01,  5.0000e-01,  1.1200e-01, ...,  1.2650e+03,
         3.0000e+00,  2.0180e+03],
       [ 8.2507e+01,  1.4220e+01, -1.8800e-01, ...,  1.2150e+03,
         0.0000e+00,  2.0180e+03],
       ...,
       [ 4.8914e+01,  4.5600e-01, -9.7000e-02, ...,  1.0450e+03,
         9.2000e+01,  2.0180e+03],
       [ 7.3932e+01,  2.3230e+00,  3.9000e-02, ...,  3.2500e+02,
         9.0000e+01,  2.0180e+03],
       [ 1.0000e+02,  6.5400e-01,  1.3200e-01, ...,  8.5500e+02,
         9.4000e+01,  2.0180e+03]])

In [45]:
data_X.shape

(770290, 16)

## Normalization

In [46]:
def column(matrix, i):
    return [row[i] for row in matrix]
def norm(lst):
    min_v = min(lst)
    max_v = max(lst)
    norm_lst = [(i-min_v)/(max_v-min_v) for i in lst]
    return norm_lst

In [47]:
curr = column(data_X, 0)
rt = np.array([norm(curr)])
for i in range(1, 15):
    if (i!=3):
        curr = column(data_X, i)
        rt = np.concatenate((rt, np.array([norm(curr)])))

In [48]:
final_rt = rt.T
final_rt.shape

(770290, 14)

In [49]:
data_X = final_rt

In [50]:
from sklearn.preprocessing import PolynomialFeatures

In [51]:
poly = PolynomialFeatures(2)

In [52]:
X = poly.fit_transform(data_X)

In [53]:
Y = data_Y

In [54]:
X.shape

(770290, 120)

In [55]:
import statsmodels.api as sm
X = sm.add_constant(X)

In [56]:
Y.shape

(770290,)

In [57]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, np.array(Y), test_size=0.2, random_state=42)
y_train  = y_train.astype(float)
y_test  = y_test.astype(float)
batch_size =len(X_train)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape )

(616232, 120) (616232,) (154058, 120) (154058,)


In [58]:
model = sm.OLS(y_train, X_train).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.335
Model:                            OLS   Adj. R-squared:                  0.335
Method:                 Least Squares   F-statistic:                     2610.
Date:                Wed, 25 Aug 2021   Prob (F-statistic):               0.00
Time:                        19:45:24   Log-Likelihood:            -1.6682e+06
No. Observations:              616232   AIC:                         3.337e+06
Df Residuals:                  616112   BIC:                         3.338e+06
Df Model:                         119                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -454.2643     21.474    -21.154      0.000    -496.353    -412.176
x1           493.6005     22.141     22.294      0.000     450.205     536.996
x2          1144.3655     28.701     39.872      0.000    1088.112    1200.619
x3           751.2588     41.066     18.294      0.000     670.771     831.747
x4          -184.1886      5.024    -36.664      0.000    -194.035    -174.342
x5          5436.6805    299.664     18.143      0.000    4849.349    6024.012
x6         -4983.6394    351.575    -14.175      0.000   -5672.716   -4294.563
x7         -2325.0718    278.696     -8.343      0.000   -2871.307   -1778.837
x8            48.2559    299.519      0.161      0.872    -538.793     635.304
x9          2303.2165     85.227     27.024      0.000    2136.174    2470.259
x10        -5985.3618    141.918    -42.175      0.000   -6263.517   -5707.206
x11         5133.7684    122.737     41.827      0.000    4893.207    5374.329
x12          228.4778      4.718     48.425      0.000     219.230     237.725
x13          -15.3417      1.899     -8.080      0.000     -19.063     -11.620
x14           78.4159      3.496     22.433      0.000      71.565      85.267
x15           20.9337      0.639     32.760      0.000      19.681      22.186
x16         -121.9070      2.149    -56.721      0.000    -126.119    -117.695
x17         -983.5331     40.945    -24.021      0.000   -1063.784    -903.283
x18           -2.1289      0.400     -5.323      0.000      -2.913      -1.345
x19          -30.7916     10.983     -2.804      0.005     -52.318      -9.266
x20          431.9401     11.198     38.573      0.000     409.993     453.888
x21          341.9327     13.133     26.036      0.000     316.193     367.673
x22         -738.8700     12.502    -59.102      0.000    -763.373    -714.367
x23          -52.0658      4.019    -12.954      0.000     -59.944     -44.188
x24           64.9081      8.272      7.846      0.000      48.694      81.122
x25           50.2480      5.571      9.019      0.000      39.328      61.168
x26           -6.4187      0.419    -15.334      0.000      -7.239      -5.598
x27           -2.1489      0.278     -7.728      0.000      -2.694      -1.604
x28            2.1844      0.259      8.445      0.000       1.677       2.691
x29          -13.3302      1.195    -11.151      0.000     -15.673     -10.987
x30        -1959.7324     53.104    -36.904      0.000   -2063.814   -1855.651
x31           -9.9215      0.803    -12.350      0.000     -11.496      -8.347
x32          -37.0104     15.772     -2.347      0.019     -67.922      -6.099
x33         -177.2416     16.949    -10.458      0.000    -210.460    -144.023
x34         -134.2875     21.252     -6.319      0.000    -175.941     -92.634
x35          326.6242     19.095     17.106      0.000     289.199     364.049
x3

In [59]:
predicted_Y = model.predict(X_test)

In [60]:
Y = y_test
len(Y)

154058

In [61]:
len(predicted_Y)

154058

## Get MAE

In [62]:
MAE = 0
for i in range(0, len(Y)):
    MAE = MAE+abs(Y[i]-predicted_Y[i])
MAE = MAE/len(Y)
print(MAE)

2.836839200146162


## Get MSE

In [63]:
MSE = 0
for i in range(0, len(Y)):
    MSE = MSE+(Y[i]-predicted_Y[i])*(Y[i]-predicted_Y[i])
MSE = MSE/len(Y)
print(MSE)

13.027481437849254
