# 2018, Random Forest

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("./final_input/rt.csv")

In [3]:
df = data

In [4]:
Y = df["temp"]
data_Y = np.array(Y.tolist())
data_Y

array([27.613 , 23.1775, 19.889 , ..., 25.954 , 22.4645, 20.319 ])

In [5]:
df.drop(df.columns[[0, 1]], axis=1, inplace=True)

/Users/carnivalbug/opt/anaconda3/lib/python3.8/site-packages/pandas/core/frame.py:4163: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [6]:
data_X = df.values

In [7]:
data_Y

array([27.613 , 23.1775, 19.889 , ..., 25.954 , 22.4645, 20.319 ])

In [8]:
data_X

array([[ 4.4761e+01,  1.0310e+00,  0.0000e+00, ...,  9.0500e+02,
         2.0000e+00,  2.0180e+03],
       [ 7.6410e+01,  5.0000e-01,  1.1200e-01, ...,  1.2650e+03,
         3.0000e+00,  2.0180e+03],
       [ 8.2507e+01,  1.4220e+01, -1.8800e-01, ...,  1.2150e+03,
         0.0000e+00,  2.0180e+03],
       ...,
       [ 4.8914e+01,  4.5600e-01, -9.7000e-02, ...,  1.0450e+03,
         9.2000e+01,  2.0180e+03],
       [ 7.3932e+01,  2.3230e+00,  3.9000e-02, ...,  3.2500e+02,
         9.0000e+01,  2.0180e+03],
       [ 1.0000e+02,  6.5400e-01,  1.3200e-01, ...,  8.5500e+02,
         9.4000e+01,  2.0180e+03]])

In [9]:
data_X.shape

(770290, 16)

## Normalization

In [10]:
def column(matrix, i):
    return [row[i] for row in matrix]
def norm(lst):
    min_v = min(lst)
    max_v = max(lst)
    norm_lst = [(i-min_v)/(max_v-min_v) for i in lst]
    return norm_lst

In [23]:
curr = column(data_X, 0)
rt = np.array([norm(curr)])
for i in range(1, 15):
    if (i!=3):
        curr = column(data_X, i)
        rt = np.concatenate((rt, np.array([norm(curr)])))

In [24]:
final_rt = rt.T
final_rt.shape

(770290, 14)

In [25]:
data_X = final_rt

In [26]:
data_X.shape

(770290, 14)

In [27]:
Y.shape

(770290,)

In [28]:
from sklearn import svm

In [29]:
from sklearn.ensemble import RandomForestClassifier

In [30]:
from sklearn.ensemble import RandomForestRegressor

In [31]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(data_X, np.array(Y), test_size=0.2, random_state=42)
y_train  = y_train.astype(float)
y_test  = y_test.astype(float)
batch_size =len(X_train)

print(X_train.shape, y_train.shape, X_test.shape, y_test.shape )

(616232, 14) (616232,) (154058, 14) (154058,)


In [33]:
regr = RandomForestRegressor(max_depth=16, random_state=0)
regr.fit(X_train, y_train)

RandomForestRegressor(max_depth=16, random_state=0)

In [34]:
predicted_Y = regr.predict(X_test)
Y = y_test.tolist()

## Get MAE

In [35]:
MAE = 0
for i in range(0, len(Y)):
    MAE = MAE+abs(Y[i]-predicted_Y[i])
MAE = MAE/len(Y)
print(MAE)

0.7939082178396567


In [36]:
MAE = 0
for i in range(0, len(Y)):
    MAE = MAE+abs(Y[i]-predicted_Y[i])
MAE = MAE/len(Y)
print(MAE)

0.7939082178396567


## Get MSE

In [37]:
MSE = 0
for i in range(0, len(Y)):
    MSE = MSE+(Y[i]-predicted_Y[i])*(Y[i]-predicted_Y[i])
MSE = MSE/len(Y)
print(MSE)

1.2682017150440772


# Vis

In [38]:
col = ["humidity","PM25","SO2","partical","light","band1","band2","band3","band4","band5","band6","band7","doc","tod","dss"]

In [39]:
import pandas as pd
from sklearn.datasets import load_boston
from sklearn.ensemble import RandomForestRegressor
from sklearn import tree
from dtreeviz.trees import dtreeviz # will be used for tree visualization
from matplotlib import pyplot as plt

In [40]:
rf = RandomForestRegressor(max_depth=3, random_state=0)

In [41]:
rf.fit(X_train, y_train)

RandomForestRegressor(max_depth=3, random_state=0)

In [ ]:
viz = dtreeviz(rf.estimators_[0], X_test, y_test, feature_names=col, target_name="Temp", title="2018, Decision Tree #1",)
viz